### PR TITLE
Initial populating of scripts and namelists

### PR DESCRIPTION
**Pull request by davegill**
This test from Kelly does a restart with the WRF model for use with automated jenkins testing. 

On a 4-processor machine, the 12 min simulation time and then the 3 min simulation restart take approximately 
3 elapsed minutes to complete with a GNU + unoptimized build. 

The domains are 75x70 and 88x79, with a 30/10 km using a 180 s dt, with the CONUS suite.

Along with the assumed 8-ish minutes to build the encompassing WRF container and then build the WRF 
executable from source, this should complete well within the 30 min target.

new file:   cases/basic/namelist.input.1
new file:   cases/basic/namelist.input.2
new file:   cases/basic/namelist.input.3
new file:   check_OK.csh
new file:   feature_testing.csh

### CODE REVIEW

**Comment by davegill** [comment]
@kkeene44
Kelly,
1. I modified the structure of the namelists a bit. Since we have real, WRF, then WRF - I named the namelists `namelist.input.1`, `namelist.input.2`, and `namelist.input.3`. This should let us be extensible for really complicated tests in the future.
2. I pulled the Thompson data into a separate directory (I called it "additional").
3. I changed the test from 6 hours long to 3 hours. Let me know if this is insufficient length.
4. The `feature_testing.csh` file is called with a few args, and should be quite general for restart runs.
```
[wrfuser@262f27491b94 ~]$ feature_testing.csh

USAGE within the standard WRF docker container:
./feature_testing.csh /wrf/wrfoutput /wrf/WRF/test/em_real /wrf/cases/basic /wrf/input/additional /wrf/input/standard mpi-4
where
The full path to the shared directory = /wrf/wrfoutput
The full path to the WRF test directory = /wrf/WRF/test/em_real
The full path to the namelist directory = /wrf/cases/basic
The full path to the additional binary data files for WRF = /wrf/input/additional
The full path to the metgrid data if a real case = /wrf/input/standard, ELSE SKIP
The combination of which parallel option (ser, omp, mpi) and how many procs = mpi-4

Please, no trailing / characters at the end of the directory names
```
5. For non-restart feature testing, we may need to come up with a new base script, or modify this one.
6. This is just a start based on your testing scripts.
7. I set it up so that we need PRs to push to `main`.

**Comment by kkeene44** [comment]
@davegill, Thanks! This all makes sense. To address the length of the simulations, most simulations don't even need to be 3 hours long. I typically run most for 12 mins, and then restart from min 09-12, checking the output at minute 12. I just completely forgot to modify that when I gave you the package.

**Comment by davegill** [comment]
@kkeene44 
Kelly,
I have made the simulations 12 min + a 3 min restart. I verify at the 12 min time. If you are OK with these, would you approve please. I would like to try to get these into the existing jenkins tests via github.

**Review by kkeene44 — APPROVED** [review]

**Comment by kkeene44** [comment]
@davegill 
Have you actually tested this script out yet, or does it have to be tested in the Jenkins framework?

**Comment by davegill** [comment]
@kkeene44 
It works in docker, but I have not pushed that up to jenkins yet. I am still tweaking it inside of docker. If I need some more changes, I am just going to BIF the approval requirement.

**Pull request merged**
